[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
converter_program = "9DRcqsJUCo8CL2xDCXpogwzLEVKRDzSyNtVgXqsXHfDs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
system-initialize-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/system-initialize-tests.ts"
config-update-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/config-update-tests.ts"
deny-list-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/deny-list-tests.ts"
conversion-price-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/conversion-price-tests.ts"
admin-change-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/admin-change-tests.ts"
system-state-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/system-state-tests.ts"
buy-sol-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/buy-sol-tests.ts"
dequeue-fills-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/dequeue-fills-tests.ts"
